const seed={hikes:[
{id:1,name:"Skyline Loop",location:"Mount Rainier, WA",date:"2026-06-01",distance:5.7,elevation:1768,duration:3.5,highest:6800,difficulty:"Moderate",rating:5,notes:"Wildflowers starting near Panorama Point.",weather:"58°F, scattered clouds",conditions:"Mostly dry with lingering snow",crowds:"Moderate",parking:"National Park pass",permit:"No",cell:"Spotty",dog:"No",water:"Water and toilets at visitor center",wildlife:"Marmots",gear:"Poles, sun hoodie",safety:"Exposed in poor weather",tags:["scenic","snowy","mountain"],lat:46.786,lng:-121.735,favorite:true},
{id:2,name:"Rattlesnake Ledge",location:"North Bend, WA",date:"2026-05-24",distance:4,elevation:1160,duration:2.25,highest:2078,difficulty:"Moderate",rating:4,notes:"Early start made all the difference.",weather:"Clear and cool",conditions:"Dry",crowds:"Crowded",parking:"Free lot",permit:"No",cell:"Good",dog:"Yes",tags:["dog-friendly","forest"],lat:47.435,lng:-121.768},
{id:3,name:"Lake 22",location:"Granite Falls, WA",date:"2026-05-11",distance:5.4,elevation:1350,duration:3.75,highest:2400,difficulty:"Moderate",rating:5,notes:"Misty, quiet, and beautifully green.",weather:"Light rain",conditions:"Muddy boardwalks",crowds:"Quiet",parking:"Forest Pass",permit:"No",cell:"None",dog:"Yes",tags:["lake","waterfall","dog-friendly"],lat:48.077,lng:-121.773},
{id:4,name:"Mount Si",location:"North Bend, WA",date:"2026-04-20",distance:7.9,elevation:3200,duration:5.25,highest:3900,difficulty:"Hard",rating:4,notes:"A strong training day. Bring more water.",weather:"Sunny",conditions:"Dry",crowds:"Moderate",parking:"Discover Pass",permit:"No",cell:"Spotty",dog:"Yes",tags:["mountain","dog-friendly"],lat:47.488,lng:-121.723}
],plans:[
{id:11,name:"Snow Lake",location:"Snoqualmie Pass, WA",date:"2026-06-14",distance:7.2,elevation:1800,duration:4,highest:4400,difficulty:"Moderate",notes:"Pack microspikes and check snow report.",weather:"Check forecast before leaving",permit:"Yes",gear:"Ten essentials, microspikes, poles",checklist:["Check snow report","Pack microspikes","Download offline map"],priority:"High",tags:["lake","snowy","permit"],lat:47.445,lng:-121.424},
{id:12,name:"Tolmie Peak",location:"Mount Rainier, WA",date:"2026-06-28",distance:6.5,elevation:1520,duration:4,highest:5900,difficulty:"Moderate",notes:"Sunrise option. Bring the camera.",permit:"No",gear:"Camera, headlamp, warm layer",checklist:["Charge camera","Pack headlamp"],priority:"Medium",tags:["scenic","mountain"],lat:46.958,lng:-121.883},
{id:13,name:"The Enchantments",location:"Leavenworth, WA",date:"2026-09-18",distance:18,elevation:4500,duration:11,highest:7800,difficulty:"Hard",notes:"Big objective. Permit and shuttle needed.",permit:"Yes",gear:"Full day kit, water filter",checklist:["Confirm permit","Book shuttle","Train weekly"],priority:"High",tags:["big objective","permit","lake"],lat:47.527,lng:-120.821}
],bucket:[
{id:21,name:"Tour du Mont Blanc",location:"France, Italy & Switzerland",difficulty:"Hard",notes:"A week walking through three countries.",season:"July–September",cost:"Multi-day travel",priority:"High",status:"Researching",tags:["international"],lat:45.832,lng:6.865},
{id:22,name:"Milford Track",location:"Fiordland, New Zealand",difficulty:"Moderate",notes:"Waterfalls, rainforest, and a proper adventure.",season:"October–April",cost:"Reservation required",priority:"Medium",status:"Dreaming",tags:["international","waterfall"],lat:-44.765,lng:167.993},
{id:23,name:"Laugavegur Trail",location:"Iceland",difficulty:"Moderate",notes:"Otherworldly color and hot springs.",season:"June–September",cost:"Huts or camping",priority:"Medium",status:"Dreaming",tags:["international"],lat:63.984,lng:-19.068}
],goals:{distance:150,elevation:32000,hikes:30,bucket:2,monthly:20},settings:{hideLocations:false,lnt:true}};
let data=JSON.parse(localStorage.getItem("nickysHikingPalData"))||structuredClone(seed);
data.goals||={distance:data.goal||150,elevation:32000,hikes:30,bucket:2,monthly:20};data.settings||={hideLocations:false,lnt:true};data.hikes.forEach(normalize);data.plans.forEach(normalize);data.bucket.forEach(normalize);
data.meta||={updatedAt:"1970-01-01T00:00:00.000Z",schemaVersion:2};
let map,detailId,importRows=[],importHeaders=[],cloudGroups=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const localKey=()=>window.HikingCloud?.user?`nickysHikingPalData:${window.HikingCloud.user.id}`:"nickysHikingPalData";
const save=()=>{data.meta={...(data.meta||{}),updatedAt:new Date().toISOString(),schemaVersion:2};localStorage.setItem(localKey(),JSON.stringify(data));window.HikingCloud?.queue()},icons=()=>window.lucide?.createIcons();
window.getAppData=()=>structuredClone(data);
window.applyCloudData=cloudData=>{if(!cloudData?.hikes)return;data=cloudData;data.goals||=structuredClone(seed.goals);data.settings||=structuredClone(seed.settings);data.hikes.forEach(normalize);data.plans.forEach(normalize);data.bucket.forEach(normalize);localStorage.setItem(localKey(),JSON.stringify(data));renderAll();toast("Cloud journal loaded")};
window.loadUserLocalData=userId=>JSON.parse(localStorage.getItem(`nickysHikingPalData:${userId}`)||"null");
window.prepareNewCloudUser=()=>{data={hikes:[],plans:[],bucket:[],goals:structuredClone(seed.goals),settings:structuredClone(seed.settings),meta:{updatedAt:new Date().toISOString(),schemaVersion:2}};localStorage.setItem(localKey(),JSON.stringify(data));renderAll()};
window.importGuestJournal=()=>{const guest=JSON.parse(localStorage.getItem("nickysHikingPalData")||"null");if(!guest?.hikes)return false;data=guest;save();renderAll();return true};
const fmtDate=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Someday";
const monthDay=d=>({month:new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short"}),day:new Date(`${d}T12:00:00`).getDate()});
const toast=msg=>{$("#toast span").textContent=msg;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2300)};
function durationSecondsOf(x){return Math.max(0,Math.round(x?.durationSeconds!=null&&Number.isFinite(+x.durationSeconds)?+x.durationSeconds:(+x?.duration||0)*3600))}
function formatDuration(x){const total=typeof x==="number"?Math.max(0,Math.round(x)):durationSecondsOf(x),hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60,parts=[];if(hours)parts.push(`${hours}h`);if(minutes||hours)parts.push(`${minutes}m`);if(seconds||!parts.length)parts.push(`${seconds}s`);return parts.join(" ")}
function formatDurationClock(x){const total=typeof x==="number"?Math.max(0,Math.round(x)):durationSecondsOf(x),hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return`${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`}
function normalize(x){x.tags||=[];x.photos||=[];x.route||=[];x.checklist||=[];x.durationSeconds=durationSecondsOf(x);x.duration=x.durationSeconds/3600;x.highest||=0}
function download(name,content,type="text/plain"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function total(items,key){return items.reduce((n,x)=>n+(+x[key]||0),0)}
function getStats(items=data.hikes){return{distance:total(items,"distance"),elevation:total(items,"elevation"),duration:total(items,"duration"),durationSeconds:items.reduce((n,x)=>n+durationSecondsOf(x),0),hikes:items.length}}
function tagsHtml(tags=[]){return tags.slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}
function greeting(){const hour=new Date().getHours();return`${hour<12?"Good morning":hour<17?"Good afternoon":"Good evening"}, Robert`}
function updateGreeting(){if($("#dashboardView").classList.contains("active"))$("#pageTitle").textContent=greeting()}
function periodHikes(period){const now=new Date(),start=new Date(now);if(period==="week")start.setDate(now.getDate()-6);if(period==="month")start.setDate(1);if(period==="year"){start.setMonth(0);start.setDate(1)}start.setHours(0,0,0,0);return period==="lifetime"?data.hikes:data.hikes.filter(h=>new Date(`${h.date}T12:00:00`)>=start)}
function applyPeriod(period){const s=getStats(periodHikes(period));$("#distanceStat").innerHTML=`${s.distance.toFixed(1)} <small>mi</small>`;$("#elevationStat").innerHTML=`${Math.round(s.elevation).toLocaleString()} <small>ft</small>`;$("#hikesStat").innerHTML=`${s.hikes} <small>hikes</small>`;$("#timeStat").innerHTML=formatDuration(s.durationSeconds)}
function renderMonthlyChart(){const now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,miles=total(data.hikes.filter(h=>h.date?.startsWith(key)),"distance");months.push({label:d.toLocaleDateString("en-US",{month:"short"}),miles})}const max=Math.max(...months.map(m=>m.miles),1),sum=months.reduce((n,m)=>n+m.miles,0);$("#chartTotal").textContent=`${sum.toFixed(1)} mi`;$("#monthlyChart").innerHTML=months.map(m=>`<div class="${m.miles===max&&m.miles>0?"best":""}" style="--h:${Math.max(4,m.miles/max*96)}%"><span>${m.miles.toFixed(m.miles%1?1:0)}</span><small>${m.label}</small></div>`).join("");$("#monthlyChart").setAttribute("aria-label",months.map(m=>`${m.label} ${m.miles.toFixed(1)} miles`).join(", "))}

function renderRecent(){$("#recentHikes").innerHTML=[...data.hikes].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(h=>`<button class="hike-card" data-detail="${h.id}"><div class="hike-thumb" ${h.photos[0]?`style="background-image:url('${h.photos[0].src}');background-size:cover"`:""}><span class="hike-number">${h.favorite?"♥ ":""}★ ${h.rating}.0</span></div><div class="hike-info"><h3>${esc(h.name)}</h3><span>${esc(h.location)} · ${fmtDate(h.date)}</span><div class="hike-meta"><span><i data-lucide="route"></i>${h.distance} mi</span><span><i data-lucide="mountain"></i>${(+h.elevation).toLocaleString()} ft</span><span>${h.difficulty}</span></div></div></button>`).join("")}
function renderHikes(){
 const term=$("#hikeSearch")?.value.toLowerCase()||"",difficulty=$("#difficultyFilter")?.value||"all",tag=$("#tagFilter")?.value||"all",sort=$("#sortHikes")?.value||"date";
 const filtered=data.hikes.filter(h=>(h.name+h.location+h.notes+(h.tags||[]).join(" ")).toLowerCase().includes(term)&&(difficulty==="all"||h.difficulty===difficulty)&&(tag==="all"||h.tags.includes(tag))).sort((a,b)=>sort==="date"?b.date.localeCompare(a.date):(+b[sort]||0)-(+a[sort]||0));
 $("#hikeLibrary").innerHTML=filtered.length?filtered.map(h=>{const d=monthDay(h.date);return `<article class="library-item" data-detail="${h.id}" tabindex="0"><div class="library-date"><strong>${d.day}</strong><span>${d.month}</span></div><div><h3>${h.favorite?"♥ ": ""}${esc(h.name)}</h3><p>${esc(h.location)} · ${esc(h.notes||"No notes yet")}</p><div class="plan-details">${tagsHtml(h.tags)}</div></div><div class="library-stats"><span>Distance<strong>${h.distance} mi</strong></span><span>Elevation<strong>${(+h.elevation).toLocaleString()} ft</strong></span><span>Difficulty<strong>${h.difficulty}</strong></span><span>Rating<strong class="rating">★ ${h.rating}.0</strong></span></div><button class="delete-button" data-delete-hike="${h.id}" aria-label="Delete ${esc(h.name)}"><i data-lucide="trash-2"></i></button></article>`}).join(""):`<article class="panel"><h3>No hikes found</h3><p>Try a different search or log your first hike.</p></article>`;
 $("#hikeCountBadge").textContent=data.hikes.length
}
function renderPlans(){
 $("#upcomingPlans").innerHTML=data.plans.slice(0,2).map(p=>{const d=monthDay(p.date);return `<div class="next-item"><div class="date-chip"><strong>${d.day}</strong><span>${d.month}</span></div><div><h4>${esc(p.name)}</h4><p>${esc(p.location)} · ${p.distance} mi</p></div><span class="difficulty">${p.difficulty}</span></div>`}).join("");
 $("#plannedList").innerHTML=data.plans.map(p=>`<article class="plan-item"><div><h3>${esc(p.name)}</h3><p>${esc(p.location)} · ${fmtDate(p.date)}</p><div class="plan-details"><span class="tag">${p.distance} miles</span><span class="tag">${(+p.elevation).toLocaleString()} ft gain</span><span class="tag">${p.difficulty}</span>${tagsHtml(p.tags)}</div><div class="checklist">${p.checklist.map((x,i)=>`<label><input type="checkbox" data-check="${p.id}:${i}" ${x.done?"checked":""}><span>${esc(x.text||x)}</span></label>`).join("")}</div>${data.settings.lnt?`<p class="lnt">Leave No Trace: pack it in, pack it out.</p>`:""}</div><div class="plan-side"><button class="complete-button" data-complete-plan="${p.id}"><i data-lucide="check"></i> Mark completed</button><button class="delete-button" data-delete-plan="${p.id}" aria-label="Delete plan"><i data-lucide="trash-2"></i></button></div></article>`).join("");
 $("#bucketList").innerHTML=data.bucket.map(b=>`<article class="bucket-card"><span class="status">${b.status}</span><span class="eyebrow">${esc(b.location)}</span><h3>${esc(b.name)}</h3><p>${esc(b.notes)}</p><div class="plan-details">${tagsHtml([b.season,b.priority,b.cost].filter(Boolean))}</div><button class="bucket-delete" data-delete-bucket="${b.id}" aria-label="Delete dream"><i data-lucide="trash-2"></i></button></article>`).join("");
 $("#planCountBadge").textContent=data.plans.length;$("#plannedTabCount").textContent=data.plans.length;$("#bucketTabCount").textContent=data.bucket.length
}
function renderStats(){
 const s=getStats(periodHikes("year")),g=data.goals,pct=Math.min(100,Math.round(s.distance/g.distance*100));
 $("#distanceStat").innerHTML=`${s.distance.toFixed(1)} <small>mi</small>`;$("#elevationStat").innerHTML=`${Math.round(s.elevation).toLocaleString()} <small>ft</small>`;$("#hikesStat").innerHTML=`${s.hikes} <small>hikes</small>`;$("#timeStat").innerHTML=formatDuration(s.durationSeconds);
 $("#rainierComparison").textContent=`${(s.elevation/14411).toFixed(1)} Mount Rainiers`;$("#heroPercent").textContent=`${pct}%`;$("#heroGoalLabel").textContent=`${s.distance.toFixed(1)} of ${g.distance} miles`;$(".sidebar-card strong").innerHTML=`<span id="sideGoalMiles">${s.distance.toFixed(1)}</span> / ${g.distance} mi`;$("#sideGoalBar").style.width=`${pct}%`;$("#sideGoalText").textContent=`${Math.max(0,g.distance-s.distance).toFixed(1)} miles to go`;
 const goalRow=(value,target,label,unit,color)=>{const p=Math.min(100,Math.round(value/target*100));return`<div class="goal-ring" style="--value:${p};--ring:${color}"><span>${p}%</span></div><div><strong>${label}</strong><span>${Math.round(value).toLocaleString()} of ${target.toLocaleString()} ${unit}</span><div class="progress-track"><span style="width:${p}%"></span></div></div>`};$("#distanceGoalRow").innerHTML=goalRow(s.distance,g.distance,"Distance explorer","miles","#e89545");$("#elevationGoalRow").innerHTML=goalRow(s.elevation,g.elevation,"Reach new heights","feet","#5e8e78");$("#hikesGoalRow").innerHTML=goalRow(s.hikes,g.hikes,"Hike more often","hikes","#5f7f9e");renderMonthlyChart()
}
function renderInsights(){
 const s=getStats(),long=[...data.hikes].sort((a,b)=>b.distance-a.distance)[0],climb=[...data.hikes].sort((a,b)=>b.elevation-a.elevation)[0],high=[...data.hikes].sort((a,b)=>b.highest-a.highest)[0],avg=s.hikes?s.distance/s.hikes:0,regions={};data.hikes.forEach(h=>regions[h.location]=(regions[h.location]||0)+1);const favorite=Object.entries(regions).sort((a,b)=>b[1]-a[1])[0]?.[0]||"None yet";
 $("#comparisonGrid").innerHTML=[["mountain-snow",`${(s.elevation/29032).toFixed(2)}× Everest`,"Lifetime elevation"],["building-2",`${(s.elevation/1454).toFixed(1)} Empire State Buildings`,"One step at a time"],["medal",`${(s.distance/26.2).toFixed(1)} marathons`,"Lifetime distance"],["route",`${avg.toFixed(1)} miles`,"Average hike"]].map(x=>`<article class="comparison-card"><i data-lucide="${x[0]}"></i><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join("");
 $("#recordList").innerHTML=[["Longest hike",long?`${long.name} · ${long.distance} mi`:"None"],["Most climbing",climb?`${climb.name} · ${climb.elevation.toLocaleString()} ft`:"None"],["Highest point",high?`${high.name} · ${(+high.highest).toLocaleString()} ft`:"None"],["Favorite region",favorite]].map(x=>`<div><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join("");
 $("#hideLocations").checked=data.settings.hideLocations;$("#lntSetting").checked=data.settings.lnt
}
function renderBriefing(){const p=[...data.plans].sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999"))[0];if(!p){$("#briefingList").innerHTML="<p>Add a planned hike to get a personalized trail briefing.</p>";return}const water=Math.max(1,Math.ceil((p.duration||p.distance/2)*.5*10)/10),gainPerMile=p.distance?Math.round(p.elevation/p.distance):0,effort=gainPerMile>500?"Very steep":gainPerMile>300?"Strenuous":gainPerMile>150?"Rolling climb":"Gentle grade";$("#briefingTitle").textContent=`Next up: ${p.name}`;$("#briefingList").innerHTML=`<div><i data-lucide="droplets"></i><span><strong>Carry about ${water} L of water</strong><small>Based on roughly 0.5 L per hiking hour; adjust for heat and access to safe water.</small></span></div><div><i data-lucide="mountain"></i><span><strong>${effort} · ${gainPerMile.toLocaleString()} ft per mile</strong><small>Pace for the grade, not just the distance.</small></span></div><div><i data-lucide="${p.permit==="Yes"?"badge-alert":"badge-check"}"></i><span><strong>${p.permit==="Yes"?"Permit or pass needs attention":"No permit currently noted"}</strong><small>Verify access, closures, parking, and trail conditions before departure.</small></span></div>`}
function renderAll(){renderRecent();renderHikes();renderPlans();renderStats();renderInsights();renderBriefing();icons()}
function setCloudState(state){
 const configured=window.HikingCloud?.configured,user=window.HikingCloud?.user,signedIn=Boolean(user);
 $("#cloudUnavailable").classList.toggle("hidden",configured);$("#cloudSignedOut").classList.toggle("hidden",!configured||signedIn);$("#cloudSignedIn").classList.toggle("hidden",!signedIn);$("#migrateDeviceBtn").classList.toggle("hidden",state!=="empty-cloud");
 $("#cloudBadge").textContent=!configured?"Local":signedIn?"Synced":"Sign in";$("#profileStatus").textContent=!configured?"Private · saved locally":signedIn?"Private · cloud sync on":"Private · cloud ready";
 if(user)$("#cloudEmail").textContent=user.email;
 const messages={syncing:"Saving to cloud…",synced:"Cloud is up to date",loaded:"Cloud journal loaded","empty-cloud":"New account · private journal is empty","local-newer":"Newer offline changes uploaded",error:"Cloud sync needs attention","signed-in":"Signed in · preparing sync","signed-out":"Sign in to sync across devices"};
 if(messages[state])$("#syncStatus").textContent=messages[state];
 icons()
}
async function renderGroups(){
 if(!window.HikingCloud?.user)return;cloudGroups=await HikingCloud.groups();
 $("#groupList").innerHTML=cloudGroups.length?(await Promise.all(cloudGroups.map(async g=>{const shared=await HikingCloud.sharedPlans(g.id);return`<article class="group-card"><div><strong>${esc(g.name)}</strong><span>Invite code: <code>${g.invite_code}</code> · ${g.role}</span></div><div class="shared-plans">${shared.length?shared.map(p=>`<span><i data-lucide="calendar"></i>${esc(p.name)} · ${esc(p.location||"Location TBD")}</span>`).join(""):"<span>No shared plans yet.</span>"}</div><div class="group-share"><select data-group-plan="${g.id}"><option value="">Choose a private plan to share</option>${data.plans.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select><button class="secondary-button" data-share-group="${g.id}"><i data-lucide="send"></i> Share plan</button></div></article>`}))).join(""):`<div class="cloud-empty compact"><p>No groups yet. Create one and share its invite code with trusted hiking partners.</p></div>`;icons()
}

function showView(name){$$(".view").forEach(v=>v.classList.remove("active"));$(`#${name}View`).classList.add("active");$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$("#pageTitle").textContent={dashboard:greeting(),hikes:"Your hiking journal",plans:"Plan the next adventure",map:"Explore your trails",insights:"Celebrate your progress"}[name];window.scrollTo({top:0,behavior:"smooth"});if(name==="map")setTimeout(initMap,50)}
function openModal(type,item=null){$("#entryForm").reset();$("#entryType").value=type;$("#editId").value=item?.id||"";$("#entryDate").value=item?.date||new Date().toISOString().slice(0,10);const cfg={completed:["Save a memory",item?"Edit completed hike":"Log a completed hike",item?"Update hike":"Save hike"],planned:["Make a plan","Add a future hike","Save plan"],bucket:["Dream a little bigger","Add to bucket list","Save dream"]}[type];$("#dialogEyebrow").textContent=cfg[0];$("#dialogTitle").textContent=cfg[1];$("#saveEntryBtn").lastChild.textContent=` ${cfg[2]}`;$("#dateField").style.display=type==="bucket"?"none":"grid";$("#ratingField").style.display=type==="completed"?"grid":"none";if(item)fillForm(item);$("#entryDialog").showModal()}
function fillForm(x){const m={Name:"name",Location:"location",Date:"date",Distance:"distance",Elevation:"elevation",Difficulty:"difficulty",Rating:"rating",Highest:"highest",Tags:"tags",Notes:"notes",Trailhead:"trailhead",Weather:"weather",Conditions:"conditions",Crowds:"crowds",Parking:"parking",Permit:"permit",Cell:"cell",Dog:"dog",Water:"water",Wildlife:"wildlife",Gear:"gear",Safety:"safety",Link:"link"};Object.entries(m).forEach(([id,key])=>{const el=$(`#entry${id}`);if(el)el.value=key==="tags"?(x.tags||[]).join(", "):(x[key]??"")});const seconds=durationSecondsOf(x);$("#entryDurationHours").value=Math.floor(seconds/3600)||"";$("#entryDurationMinutes").value=Math.floor(seconds%3600/60)||"";$("#entryDurationSeconds").value=seconds%60||""}
async function readPhotos(files){return Promise.all([...files].slice(0,4).map(file=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,src:r.result,caption:file.name});r.readAsDataURL(file)})))}
async function readRoute(file){if(!file)return[];const xml=new DOMParser().parseFromString(await file.text(),"text/xml"),pts=[...xml.querySelectorAll("trkpt, rtept, Point coordinates")];return pts.map(p=>{if(p.matches("Point coordinates")){const [lng,lat,ele]=p.textContent.trim().split(",").map(Number);return{lat,lng,ele}}return{lat:+p.getAttribute("lat"),lng:+p.getAttribute("lon"),ele:+p.querySelector("ele")?.textContent||0}}).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng))}
function formItem(){const durationSeconds=(+$("#entryDurationHours").value||0)*3600+(+$("#entryDurationMinutes").value||0)*60+(+$("#entryDurationSeconds").value||0);return{name:$("#entryName").value,location:$("#entryLocation").value,date:$("#entryDate").value||new Date().toISOString().slice(0,10),distance:+$("#entryDistance").value,elevation:+$("#entryElevation").value,difficulty:$("#entryDifficulty").value,rating:+$("#entryRating").value,durationSeconds,duration:durationSeconds/3600,highest:+$("#entryHighest").value,tags:$("#entryTags").value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean),notes:$("#entryNotes").value,trailhead:$("#entryTrailhead").value,weather:$("#entryWeather").value,conditions:$("#entryConditions").value,crowds:$("#entryCrowds").value,parking:$("#entryParking").value,permit:$("#entryPermit").value,cell:$("#entryCell").value,dog:$("#entryDog").value,water:$("#entryWater").value,wildlife:$("#entryWildlife").value,gear:$("#entryGear").value,safety:$("#entrySafety").value,link:$("#entryLink").value}}
function showDetail(id){const h=data.hikes.find(x=>x.id==id);if(!h)return;detailId=h.id;$("#detailTitle").textContent=h.name;$("#detailLocation").textContent=`${h.location} · ${fmtDate(h.date)}`;$("#detailPhotos").innerHTML=h.photos.length?h.photos.map(p=>`<img src="${p.src}" alt="${esc(p.caption||`${h.name} hiking photo`)}">`).join(""):`<div class="empty-photo"><i data-lucide="image"></i><span>No photos yet</span></div>`;$("#detailStats").innerHTML=[["route",`${h.distance} mi`],["mountain",`${(+h.elevation).toLocaleString()} ft gain`],["clock",formatDuration(h)],["move-up",`${(+h.highest||0).toLocaleString()} ft high`]].map(x=>`<span><i data-lucide="${x[0]}"></i><strong>${x[1]}</strong></span>`).join("");$("#detailBody").innerHTML=`<section><h3>Reflection</h3><p>${esc(h.notes||"No reflection yet.")}</p><div class="plan-details">${tagsHtml(h.tags)}</div></section><section><h3>Conditions & weather</h3><p>${esc(h.conditions||"No condition notes")} · ${esc(h.weather||"No weather notes")} · ${esc(h.crowds||"Unknown")} crowds</p></section><section><h3>Practical notes</h3><dl><dt>Parking / pass</dt><dd>${esc(h.parking||"Unknown")}</dd><dt>Permit</dt><dd>${esc(h.permit||"Unknown")}</dd><dt>Cell service</dt><dd>${esc(h.cell||"Unknown")}</dd><dt>Water / bathrooms</dt><dd>${esc(h.water||"Unknown")}</dd><dt>Safety / wildlife</dt><dd>${esc([h.safety,h.wildlife].filter(Boolean).join(" · ")||"No notes")}</dd><dt>Gear</dt><dd>${esc(h.gear||"No notes")}</dd></dl></section>`;$("#gpxExportBtn").disabled=!h.route.length;$("#detailDialog").showModal();icons()}
function initMap(){if(!window.L)return;if(map){map.remove();map=null}map=L.map("map",{zoomControl:false}).setView([47.3,-121.7],7);L.control.zoom({position:"bottomright"}).addTo(map);const standard=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors"}).addTo(map),topo=L.tileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenTopoMap"});L.control.layers({"Standard":standard,"Topographic":topo}).addTo(map);[["hikes","#277a59","Completed"],["plans","#e89545","Planned"],["bucket","#7189ad","Bucket list"]].forEach(([key,color,label])=>data[key].forEach(item=>{const offset=data.settings.hideLocations ? .025 : 0,first=item.route[0],lat=(first?.lat||item.lat),lng=(first?.lng||item.lng);if(!lat)return;const icon=L.divIcon({className:"",html:`<div class="map-pin" style="background:${color}"></div>`,iconSize:[20,20],iconAnchor:[10,18]});L.marker([lat+offset,lng+offset],{icon}).addTo(map).bindPopup(`<strong>${esc(item.name)}</strong><br><small>${label} · ${esc(item.location)}</small>`);if(item.route.length)L.polyline(item.route.map(p=>[p.lat+offset,p.lng+offset]),{color,weight:4}).addTo(map)}))}
function gpxFor(h){const pts=h.route.map(p=>`<trkpt lat="${p.lat}" lon="${p.lng}"><ele>${p.ele||0}</ele></trkpt>`).join("");return`<?xml version="1.0"?><gpx version="1.1" creator="Nickys Hiking Pal"><trk><name>${esc(h.name)}</name><trkseg>${pts}</trkseg></trk></gpx>`}
const importFields=[["name","Hike name"],["date","Date completed"],["location","Location / region"],["distance","Distance (miles)"],["elevation","Elevation gain (feet)"],["duration","Duration (H:MM:SS or hours)"],["highest","Highest point (feet)"],["difficulty","Difficulty"],["rating","Personal rating"],["notes","Notes / reflection"],["weather","Weather"],["conditions","Trail conditions"],["crowds","Crowd level"],["parking","Parking / pass"],["permit","Permit required"],["cell","Cell service"],["dog","Dog friendly"],["water","Water / bathrooms"],["wildlife","Wildlife / bugs"],["gear","Gear / companions"],["safety","Safety notes"],["tags","Tags"],["lat","Latitude"],["lng","Longitude"],["trailhead","Trailhead"],["link","Reference link"]];
const synonyms={name:["hike","hike name","trail","trail name","name"],date:["date","date completed","completed","hike date"],location:["location","area","region","park","state"],distance:["distance","miles","mileage","distance mi"],elevation:["elevation","elevation gain","gain","vertical","vert"],duration:["duration","time","hours","hiking time","elapsed time","time taken","duration (h:mm:ss)"],highest:["highest","highest point","max elevation","peak elevation"],difficulty:["difficulty","rating difficulty"],rating:["rating","personal rating","stars"],notes:["notes","comments","reflection","review"],weather:["weather","weather notes"],conditions:["conditions","trail conditions"],crowds:["crowds","crowd level"],parking:["parking","parking notes","pass"],permit:["permit","permit required"],cell:["cell","cell service","service"],dog:["dog","dog friendly","dogs"],water:["water","bathrooms","water availability"],wildlife:["wildlife","bugs","mosquitoes"],gear:["gear","companions","hiked with"],safety:["safety","emergency","exposure"],tags:["tags","features","type"],lat:["latitude","lat"],lng:["longitude","lng","lon"],trailhead:["trailhead","start"],link:["link","url","reference"]};
function autoColumn(field){const choices=synonyms[field]||[field],normalized=importHeaders.map(h=>String(h).trim().toLowerCase());let i=normalized.findIndex(h=>choices.includes(h));if(i<0)i=normalized.findIndex(h=>choices.some(s=>h.includes(s)));return i<0?"":importHeaders[i]}
function renderMapping(){const options=`<option value="">Not included</option>${importHeaders.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join("")}`;$("#mappingGrid").innerHTML=importFields.map(([key,label])=>`<label>${label}<select data-map-field="${key}">${options}</select></label>`).join("");$$("[data-map-field]").forEach(s=>s.value=autoColumn(s.dataset.mapField));$("#importPreview").innerHTML=importRows.slice(0,3).map(row=>`<div><strong>${esc(row[autoColumn("name")]||"Unnamed hike")}</strong><span>${esc(row[autoColumn("date")]||"No date")} · ${esc(row[autoColumn("distance")]||"No distance")}</span></div>`).join("");icons()}
function parseNum(v){const n=Number(String(v??"").replace(/,/g,"").match(/-?\d+(\.\d+)?/)?.[0]);return Number.isFinite(n)?n:0}
function parseDurationSeconds(v){if(v==null||v==="")return 0;const text=String(v).trim().toLowerCase();if(text.includes(":")){const parts=text.split(":").map(Number);if(parts.every(Number.isFinite)){const [hours=0,minutes=0,seconds=0]=parts;return Math.max(0,Math.round(hours*3600+minutes*60+seconds))}}const units=text.match(/(?:(\d+(?:\.\d+)?)\s*h(?:ours?)?)?\s*(?:(\d+(?:\.\d+)?)\s*m(?:in(?:utes?)?)?)?\s*(?:(\d+(?:\.\d+)?)\s*s(?:ec(?:onds?)?)?)?/);if(units&&(units[1]||units[2]||units[3]))return Math.max(0,Math.round((+units[1]||0)*3600+(+units[2]||0)*60+(+units[3]||0)));return Math.max(0,Math.round(parseNum(v)*3600))}
function parseDate(v){if(!v)return"";if(typeof v==="number"&&window.XLSX)return XLSX.SSF.format("yyyy-mm-dd",v);const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toISOString().slice(0,10)}
function mappedHikes(){const mapping=Object.fromEntries($$("[data-map-field]").map(s=>[s.dataset.mapField,s.value]));return importRows.filter(r=>r[mapping.name]).map((r,i)=>{const get=k=>mapping[k]?r[mapping[k]]:"",durationSeconds=parseDurationSeconds(get("duration")),h={id:Date.now()+i,name:String(get("name")).trim(),date:parseDate(get("date"))||new Date().toISOString().slice(0,10),location:String(get("location")||"Unknown location").trim(),distance:parseNum(get("distance")),elevation:parseNum(get("elevation")),durationSeconds,duration:durationSeconds/3600,highest:parseNum(get("highest")),difficulty:String(get("difficulty")||"Moderate"),rating:Math.min(5,Math.max(1,parseNum(get("rating"))||3)),notes:String(get("notes")||""),weather:String(get("weather")||""),conditions:String(get("conditions")||""),crowds:String(get("crowds")||"Unknown"),parking:String(get("parking")||""),permit:String(get("permit")||"Unknown"),cell:String(get("cell")||"Unknown"),dog:String(get("dog")||"Unknown"),water:String(get("water")||""),wildlife:String(get("wildlife")||""),gear:String(get("gear")||""),safety:String(get("safety")||""),tags:String(get("tags")||"").split(/[,;|]/).map(x=>x.trim().toLowerCase()).filter(Boolean),lat:parseNum(get("lat"))||undefined,lng:parseNum(get("lng"))||undefined,trailhead:String(get("trailhead")||""),link:String(get("link")||"")};normalize(h);return h})}
const weatherCodes={0:["Sun","sun"],1:["Mostly clear","sun"],2:["Partly cloudy","cloud-sun"],3:["Overcast","cloud"],45:["Foggy","cloud-fog"],48:["Rime fog","cloud-fog"],51:["Light drizzle","cloud-drizzle"],53:["Drizzle","cloud-drizzle"],55:["Heavy drizzle","cloud-rain"],61:["Light rain","cloud-rain"],63:["Rain","cloud-rain"],65:["Heavy rain","cloud-rain-wind"],71:["Light snow","cloud-snow"],73:["Snow","cloud-snow"],75:["Heavy snow","cloud-snow"],80:["Rain showers","cloud-rain"],81:["Rain showers","cloud-rain"],82:["Heavy showers","cloud-rain-wind"],95:["Thunderstorms","cloud-lightning"]};
async function fetchWeather(lat=47.6062,lng=-122.3321,label="Seattle area"){try{$("#weatherCondition").textContent="Checking current conditions…";const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m&daily=precipitation_probability_max,sunrise,sunset&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=1`;const w=await fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()}),c=w.current,d=w.daily,info=weatherCodes[c.weather_code]||["Current conditions","cloud-sun"],sunrise=new Date(d.sunrise[0]).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}),sunset=new Date(d.sunset[0]).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});$("#weatherTemp").textContent=`${Math.round(c.temperature_2m)}°`;$("#weatherCondition").textContent=`${info[0]} · ${label}`;$("#weatherFeels").textContent=`${Math.round(c.apparent_temperature)}°`;$("#weatherWind").textContent=`${Math.round(c.wind_speed_10m)} mph`;$("#weatherRain").textContent=`${d.precipitation_probability_max[0]??0}%`;$("#weatherDaylight").textContent=`${sunrise}–${sunset}`;$("#weatherIcon").innerHTML=`<i data-lucide="${info[1]}"></i>`;$("#weatherAdvice").textContent=c.wind_speed_10m>20?"Windy at low elevation; exposed ridges may be much stronger.":d.precipitation_probability_max[0]>50?"Rain is likely. Pack a shell and protect insulation.":"Trailhead weather can differ sharply from mountain conditions.";data.settings.weather={lat,lng,label};save();icons()}catch{$("#weatherCondition").textContent="Weather unavailable right now";$("#weatherAdvice").textContent="Check an official mountain forecast before leaving."}}

document.addEventListener("click",async e=>{const view=e.target.closest("[data-view]")?.dataset.view||e.target.closest("[data-view-jump]")?.dataset.viewJump||e.target.closest("[data-view-link]")?.dataset.viewLink;if(view){e.preventDefault();showView(view)}const modal=e.target.closest("[data-open-modal]")?.dataset.openModal;if(modal)openModal(modal);const detail=e.target.closest("[data-detail]")?.dataset.detail;if(detail&&!e.target.closest("[data-delete-hike]"))showDetail(detail);const del=e.target.closest("[data-delete-hike]")?.dataset.deleteHike;if(del&&confirm("Delete this hike from your journal?")){data.hikes=data.hikes.filter(h=>h.id!=del);save();renderAll();toast("Hike removed")}const dp=e.target.closest("[data-delete-plan]")?.dataset.deletePlan;if(dp){data.plans=data.plans.filter(x=>x.id!=dp);save();renderAll();toast("Plan removed")}const db=e.target.closest("[data-delete-bucket]")?.dataset.deleteBucket;if(db){data.bucket=data.bucket.filter(x=>x.id!=db);save();renderAll();toast("Dream removed")}const complete=e.target.closest("[data-complete-plan]")?.dataset.completePlan;if(complete){const p=data.plans.find(x=>x.id==complete);data.plans=data.plans.filter(x=>x.id!=complete);data.hikes.unshift({...p,id:Date.now(),date:new Date().toISOString().slice(0,10),rating:5,notes:`Completed from plan. ${p.notes}`});save();renderAll();toast(`${p.name} moved to completed hikes`)}if(e.target.closest("[data-close-detail]"))$("#detailDialog").close();if(e.target.closest("[data-close-entry]"))$("#entryDialog").close();if(e.target.closest("[data-close-sheet]"))$("#spreadsheetDialog").close();if(e.target.closest("[data-close-cloud]"))$("#cloudDialog").close();const groupId=e.target.closest("[data-share-group]")?.dataset.shareGroup;if(groupId){const planId=+document.querySelector(`[data-group-plan="${groupId}"]`).value,plan=data.plans.find(p=>p.id===planId);if(!plan){toast("Choose a plan to share");return}const {error}=await HikingCloud.sharePlan(groupId,plan);toast(error?"Could not share that plan":"Plan shared with group");if(!error)renderGroups()}});
$("#entryForm").addEventListener("submit",async e=>{e.preventDefault();const type=$("#entryType").value,id=+$("#editId").value,item={id:id||Date.now(),...formItem()},old=id?data.hikes.find(x=>x.id===id):null;item.photos=(await readPhotos($("#entryPhotos").files)).concat(old?.photos||[]);item.route=(await readRoute($("#entryRoute").files[0]));if(!item.route.length)item.route=old?.route||[];if(item.route[0]){item.lat=item.route[0].lat;item.lng=item.route[0].lng}if(type==="completed"){data.hikes=id?data.hikes.map(x=>x.id===id?item:x):[item,...data.hikes]}else if(type==="planned"){item.checklist=(item.gear||"Ten essentials, water, offline map").split(",").map(x=>({text:x.trim(),done:false}));data.plans.unshift(item)}else data.bucket.unshift({...item,status:"Dreaming",season:item.weather||"Any season",priority:"Medium"});try{save()}catch{item.photos=[];save();toast("Saved without photos because browser storage is full")}renderAll();$("#entryDialog").close();toast(id?"Hike updated":type==="completed"?"Hike saved to your journal":type==="planned"?"Plan added to your calendar":"Dream added to your bucket list")});
["hikeSearch","difficultyFilter","tagFilter","sortHikes"].forEach(id=>$(`#${id}`).addEventListener(id==="hikeSearch"?"input":"change",()=>{renderHikes();icons()}));
$$("[data-plan-tab]").forEach(b=>b.addEventListener("click",()=>{$$("[data-plan-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#plannedList").classList.toggle("hidden",b.dataset.planTab!=="planned");$("#bucketList").classList.toggle("hidden",b.dataset.planTab!=="bucket")}));
document.addEventListener("change",e=>{if(e.target.dataset.check){const [id,i]=e.target.dataset.check.split(":");const p=data.plans.find(x=>x.id==id);p.checklist[i]=typeof p.checklist[i]==="string"?{text:p.checklist[i],done:e.target.checked}:{...p.checklist[i],done:e.target.checked};save()}});
$("#exportBtn").addEventListener("click",()=>{download("nickys-hiking-pal-backup.json",JSON.stringify(data,null,2),"application/json");toast("App backup downloaded")});$("#importBtn").addEventListener("click",()=>{$("#backupInput").value="";$("#backupInput").click()});$("#backupInput").addEventListener("change",async e=>{if(!e.target.files[0])return;try{const restored=JSON.parse(await e.target.files[0].text());if(!Array.isArray(restored.hikes)||!confirm("Restore this app backup? This replaces the hikes, plans, goals, and settings currently stored in this browser."))return;data=restored;data.hikes.forEach(normalize);data.plans.forEach(normalize);data.bucket.forEach(normalize);save();renderAll();toast("App backup restored")}catch{toast("That app backup could not be read")}});
$("#sheetImportBtn").addEventListener("click",()=>{$("#importStart").classList.remove("hidden");$("#mappingStep").classList.add("hidden");$("#spreadsheetInput").value="";$("#spreadsheetDialog").showModal();icons()});
$("#spreadsheetInput").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;if(!window.XLSX){toast("Spreadsheet reader did not load. Check your connection.");return}try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true}),sheet=wb.Sheets[wb.SheetNames[0]];importRows=XLSX.utils.sheet_to_json(sheet,{defval:"",raw:false});importHeaders=importRows.length?Object.keys(importRows[0]):[];if(!importRows.length)throw Error();$("#importSummary").textContent=`${importRows.length.toLocaleString()} rows found`;$("#importSheetName").textContent=`${file.name} · ${wb.SheetNames[0]}`;$("#importStart").classList.add("hidden");$("#mappingStep").classList.remove("hidden");renderMapping()}catch{toast("We could not read that spreadsheet. Try saving it as .xlsx or .csv.")}});
$("#confirmImportBtn").addEventListener("click",()=>{let hikes=mappedHikes();if(!hikes.length){toast("Map a hike-name column before importing.");return}if($("#skipDuplicates").checked&&!$("#replaceOnImport").checked){const keys=new Set(data.hikes.map(h=>`${h.name}|${h.date}|${h.location}`.toLowerCase()));hikes=hikes.filter(h=>!keys.has(`${h.name}|${h.date}|${h.location}`.toLowerCase()))}if(!hikes.length){toast("No new hikes to import; exact duplicates were skipped.");return}data.hikes=$("#replaceOnImport").checked?hikes:[...hikes,...data.hikes];save();renderAll();$("#spreadsheetDialog").close();showView("hikes");toast(`${hikes.length} hikes imported from spreadsheet`)});
$("#templateBtn").addEventListener("click",()=>download("hiking-history-import-template.csv","Hike Name,Date Completed,Location,Distance,Elevation Gain,Duration (H:MM:SS),Highest Point,Difficulty,Personal Rating,Notes,Weather,Trail Conditions,Crowd Level,Parking,Permit Required,Cell Service,Dog Friendly,Water Availability,Wildlife,Gear, safety,Tags,Latitude,Longitude,Trailhead,Reference Link\nSkyline Loop,2026-06-01,\"Mount Rainier, WA\",5.7,1768,03:30:00,6800,Moderate,5,Beautiful day,Partly cloudy,Dry,Moderate,National Park pass,No,Spotty,No,Visitor center,Marmots,\"Poles, sun hoodie\",Exposed ridge,\"scenic, mountain\",46.786,-121.735,Paradise,","text/csv"));
$("#csvExportBtn").addEventListener("click",()=>download("hike-history.csv",["Name,Date,Location,Distance,Elevation,Duration (H:MM:SS),Duration Hours,Difficulty,Rating,Tags",...data.hikes.map(h=>[h.name,h.date,h.location,h.distance,h.elevation,formatDurationClock(h),h.duration,h.difficulty,h.rating,h.tags.join("|")].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n"),"text/csv"));
$("#searchToggle").addEventListener("click",()=>{showView("hikes");setTimeout(()=>$("#hikeSearch").focus(),100)});$("#editGoalsBtn").addEventListener("click",()=>{for(const [key,label] of [["distance","Annual miles"],["elevation","Annual elevation feet"],["hikes","Annual hike count"],["bucket","Annual bucket-list completions"],["monthly","Monthly miles"]]){const next=prompt(`${label}:`,data.goals[key]);if(next&&+next>0)data.goals[key]=+next}save();renderStats();toast("Goals updated")});
$("#privacyBtn").addEventListener("click",()=>{showView("insights");toast("Your data stays in this browser until you export it")});$("#hideLocations").addEventListener("change",e=>{data.settings.hideLocations=e.target.checked;save();toast(e.target.checked?"Exact trailheads hidden":"Exact trailheads visible")});$("#lntSetting").addEventListener("change",e=>{data.settings.lnt=e.target.checked;save();renderPlans();icons()});$("#printPlanBtn").addEventListener("click",()=>window.print());
$("#cloudBtn").addEventListener("click",()=>{$("#cloudDialog").showModal();setCloudState(window.HikingCloud?.user?"signed-in":"signed-out");if(window.HikingCloud?.user)renderGroups()});
$("#authForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await HikingCloud.signIn($("#authEmail").value,$("#authPassword").value);toast(error?error.message:"Signed in. Syncing your journal…")});
$("#signUpBtn").addEventListener("click",async()=>{const {error}=await HikingCloud.signUp($("#authEmail").value,$("#authPassword").value);toast(error?error.message:"Account created. Check your email if confirmation is enabled.")});
$("#signOutBtn").addEventListener("click",async()=>{await HikingCloud.signOut();location.reload()});
$("#migrateDeviceBtn").addEventListener("click",async()=>{if(!confirm("Import the journal currently saved in this browser into this account?"))return;if(window.importGuestJournal()){await HikingCloud.syncNow();setCloudState("synced");toast("Device journal imported into this account")}else toast("No guest journal was found on this device")});
$("#syncNowBtn").addEventListener("click",async()=>toast(await HikingCloud.syncNow()?"Cloud sync complete":"Cloud sync failed"));
$("#createGroupBtn").addEventListener("click",async()=>{const name=$("#newGroupName").value.trim();if(!name){toast("Enter a group name");return}const {error}=await HikingCloud.createGroup(name);toast(error?error.message:"Group created");if(!error){$("#newGroupName").value="";renderGroups()}});
$("#joinGroupBtn").addEventListener("click",async()=>{const code=$("#joinGroupCode").value.trim();if(!code){toast("Enter an invite code");return}const {error}=await HikingCloud.joinGroup(code);toast(error?error.message:"Joined hiking group");if(!error){$("#joinGroupCode").value="";renderGroups()}});
$("#refreshWeatherBtn").addEventListener("click",()=>{if(!navigator.geolocation){toast("Location is not available in this browser");return}$("#weatherCondition").textContent="Waiting for location permission…";navigator.geolocation.getCurrentPosition(p=>fetchWeather(p.coords.latitude,p.coords.longitude,"your location"),()=>{toast("Location was not shared. Showing Seattle-area weather.");fetchWeather()}, {enableHighAccuracy:false,timeout:10000,maximumAge:900000})});
$("#favoriteBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);h.favorite=!h.favorite;save();renderAll();showDetail(detailId);toast(h.favorite?"Added to favorites":"Removed from favorites")});$("#duplicateBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);data.plans.unshift({...structuredClone(h),id:Date.now(),date:new Date().toISOString().slice(0,10),checklist:[{text:"Check current conditions",done:false},{text:"Pack ten essentials",done:false}]});save();renderAll();$("#detailDialog").close();toast("Hike duplicated as a plan")});$("#gpxExportBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);if(h.route.length)download(`${h.name.replace(/\W+/g,"-").toLowerCase()}.gpx`,gpxFor(h),"application/gpx+xml")});$("#editHikeBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);$("#detailDialog").close();openModal("completed",h)});
$$("[data-period]").forEach(b=>b.addEventListener("click",()=>{$$("[data-period]").forEach(x=>x.classList.toggle("active",x===b));applyPeriod(b.dataset.period)}));
$("#todayLabel").textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"});updateGreeting();setInterval(updateGreeting,60000);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});renderAll();HikingCloud.on((event)=>{setCloudState(event);if(event==="signed-in")renderGroups()});HikingCloud.init();const savedWeather=data.settings.weather;savedWeather?fetchWeather(savedWeather.lat,savedWeather.lng,savedWeather.label):fetchWeather();
