const seed={hikes:[
{id:1,name:"Skyline Loop",location:"Mount Rainier, WA",date:"2026-06-01",distance:5.7,elevation:1768,duration:3.5,highest:6800,difficulty:"Moderate",rating:5,notes:"Wildflowers starting near Panorama Point.",weather:"58°F, scattered clouds",conditions:"Mostly dry with lingering snow",crowds:"Moderate",parking:"National Park pass",permit:"No",cell:"Spotty",dog:"No",water:"Water and toilets at visitor center",wildlife:"Marmots",gear:"Poles, sun hoodie",safety:"Exposed in poor weather",tags:["scenic","snowy","mountain"],lat:46.786,lng:-121.735,favorite:true},
{id:2,name:"Rattlesnake Ledge",location:"North Bend, WA",date:"2026-05-24",distance:4,elevation:1160,duration:2.25,highest:2078,difficulty:"Moderate",rating:4,notes:"Early start made all the difference.",weather:"Clear and cool",conditions:"Dry",crowds:"Crowded",parking:"Free lot",permit:"No",cell:"Good",dog:"Yes",tags:["dog-friendly","forest"],lat:47.435,lng:-121.768},
{id:3,name:"Lake 22",location:"Granite Falls, WA",date:"2026-05-11",distance:5.4,elevation:1350,duration:3.75,highest:2400,difficulty:"Moderate",rating:5,notes:"Misty, quiet, and beautifully green.",weather:"Light rain",conditions:"Muddy boardwalks",crowds:"Quiet",parking:"Forest Pass",permit:"No",cell:"None",dog:"Yes",tags:["lake","waterfall","dog-friendly"],lat:48.077,lng:-121.773},
{id:4,name:"Mount Si",location:"North Bend, WA",date:"2026-04-20",distance:7.9,elevation:3200,duration:5.25,highest:3900,difficulty:"Hard",rating:4,notes:"A strong training day. Bring more water.",weather:"Sunny",conditions:"Dry",crowds:"Moderate",parking:"Discover Pass",permit:"No",cell:"Spotty",dog:"Yes",tags:["mountain","dog-friendly"],lat:47.488,lng:-121.723}
],plans:[
{id:11,name:"Snow Lake",location:"Snoqualmie Pass, WA",date:"2026-06-14",distance:7.2,elevation:1800,duration:4,highest:4400,difficulty:"Moderate",notes:"Pack microspikes and check snow report.",weather:"Check forecast before leaving",permit:"Yes",gear:"Ten essentials, microspikes, poles",checklist:["Check snow report","Pack microspikes","Download offline map"],priority:"High",tags:["lake","snowy","permit"],lat:47.445,lng:-121.424},
{id:12,name:"Tolmie Peak",location:"Mount Rainier, WA",date:"2026-06-28",distance:6.5,elevation:1520,duration:4,highest:5900,difficulty:"Moderate",notes:"Sunrise option. Bring the camera.",permit:"No",gear:"Camera, headlamp, warm layer",checklist:["Charge camera","Pack headlamp"],priority:"Medium",tags:["scenic","mountain"],lat:46.958,lng:-121.883},
{id:13,name:"The Enchantments",location:"Leavenworth, WA",date:"2026-09-18",distance:18,elevation:4500,duration:11,highest:7800,difficulty:"Hard",notes:"Big objective. Permit and shuttle needed.",permit:"Yes",gear:"Full day kit, water filter",checklist:["Confirm permit","Book shuttle","Train weekly"],priority:"High",tags:["big objective","permit","lake"],lat:47.527,lng:-120.821}
],bucket:[
{id:21,name:"Tour du Mont Blanc",location:"France, Italy & Switzerland",difficulty:"Hard",notes:"A week walking through three countries.",season:"July–September",cost:"Multi-day travel",priority:"High",status:"Researching",tags:["international"],lat:45.832,lng:6.865},
{id:22,name:"Milford Track",location:"Fiordland, New Zealand",difficulty:"Moderate",notes:"Waterfalls, rainforest, and a proper adventure.",season:"October–April",cost:"Reservation required",priority:"Medium",status:"Dreaming",tags:["international","waterfall"],lat:-44.765,lng:167.993},
{id:23,name:"Laugavegur Trail",location:"Iceland",difficulty:"Moderate",notes:"Otherworldly color and hot springs.",season:"June–September",cost:"Huts or camping",priority:"Medium",status:"Dreaming",tags:["international"],lat:63.984,lng:-19.068}
],goals:{distance:150,elevation:32000,hikes:30,bucket:2,monthly:20},settings:{hideLocations:false,lnt:true}};
let data=JSON.parse(localStorage.getItem("nickysHikingPalData"))||structuredClone(seed);
data.goals||={distance:data.goal||150,elevation:32000,hikes:30,bucket:2,monthly:20};data.settings||={hideLocations:false,lnt:true};data.hikes.forEach(normalize);data.plans.forEach(normalize);data.bucket.forEach(normalize);
let map,detailId;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const save=()=>localStorage.setItem("nickysHikingPalData",JSON.stringify(data)),icons=()=>window.lucide?.createIcons();
const fmtDate=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Someday";
const monthDay=d=>({month:new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short"}),day:new Date(`${d}T12:00:00`).getDate()});
const toast=msg=>{$("#toast span").textContent=msg;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2300)};
function normalize(x){x.tags||=[];x.photos||=[];x.route||=[];x.checklist||=[];x.duration||=0;x.highest||=0}
function download(name,content,type="text/plain"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function total(items,key){return items.reduce((n,x)=>n+(+x[key]||0),0)}
function getStats(items=data.hikes){return{distance:total(items,"distance"),elevation:total(items,"elevation"),duration:total(items,"duration"),hikes:items.length}}
function tagsHtml(tags=[]){return tags.slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}

function renderRecent(){$("#recentHikes").innerHTML=[...data.hikes].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(h=>`<button class="hike-card" data-detail="${h.id}"><div class="hike-thumb" ${h.photos[0]?`style="background-image:url('${h.photos[0].src}');background-size:cover"`:""}><span class="hike-number">${h.favorite?"♥ ":""}★ ${h.rating}.0</span></div><div class="hike-info"><h3>${esc(h.name)}</h3><span>${esc(h.location)} · ${fmtDate(h.date)}</span><div class="hike-meta"><span><i data-lucide="route"></i>${h.distance} mi</span><span><i data-lucide="mountain"></i>${(+h.elevation).toLocaleString()} ft</span><span>${h.difficulty}</span></div></div></button>`).join("")}
function renderHikes(){
 const term=$("#hikeSearch")?.value.toLowerCase()||"",difficulty=$("#difficultyFilter")?.value||"all",tag=$("#tagFilter")?.value||"all",sort=$("#sortHikes")?.value||"date";
 const filtered=data.hikes.filter(h=>(h.name+h.location+h.notes+(h.tags||[]).join(" ")).toLowerCase().includes(term)&&(difficulty==="all"||h.difficulty===difficulty)&&(tag==="all"||h.tags.includes(tag))).sort((a,b)=>sort==="date"?b.date.localeCompare(a.date):(+b[sort]||0)-(+a[sort]||0));
 $("#hikeLibrary").innerHTML=filtered.length?filtered.map(h=>{const d=monthDay(h.date);return `<article class="library-item" data-detail="${h.id}" tabindex="0"><div class="library-date"><strong>${d.day}</strong><span>${d.month}</span></div><div><h3>${h.favorite?"♥ ": ""}${esc(h.name)}</h3><p>${esc(h.location)} · ${esc(h.notes||"No notes yet")}</p><div class="plan-details">${tagsHtml(h.tags)}</div></div><div class="library-stats"><span>Distance<strong>${h.distance} mi</strong></span><span>Elevation<strong>${(+h.elevation).toLocaleString()} ft</strong></span><span>Difficulty<strong>${h.difficulty}</strong></span><span>Rating<strong class="rating">★ ${h.rating}.0</strong></span></div><button class="delete-button" data-delete-hike="${h.id}" aria-label="Delete ${esc(h.name)}"><i data-lucide="trash-2"></i></button></article>`}).join(""):`<article class="panel"><h3>No hikes found</h3><p>Try a different search or log your first hike.</p></article>`;
 $("#hikeCountBadge").textContent=data.hikes.length
}
function renderPlans(){
 $("#upcomingPlans").innerHTML=data.plans.slice(0,2).map(p=>{const d=monthDay(p.date);return `<div class="next-item"><div class="date-chip"><strong>${d.day}</strong><span>${d.month}</span></div><div><h4>${esc(p.name)}</h4><p>${esc(p.location)} · ${p.distance} mi</p></div><span class="difficulty">${p.difficulty}</span></div>`}).join("");
 $("#plannedList").innerHTML=data.plans.map(p=>`<article class="plan-item"><div><h3>${esc(p.name)}</h3><p>${esc(p.location)} · ${fmtDate(p.date)}</p><div class="plan-details"><span class="tag">${p.distance} miles</span><span class="tag">${(+p.elevation).toLocaleString()} ft gain</span><span class="tag">${p.difficulty}</span>${tagsHtml(p.tags)}</div><div class="checklist">${p.checklist.map((x,i)=>`<label><input type="checkbox" data-check="${p.id}:${i}" ${x.done?"checked":""}><span>${esc(x.text||x)}</span></label>`).join("")}</div>${data.settings.lnt?`<p class="lnt">Leave No Trace: pack it in, pack it out.</p>`:""}</div><div class="plan-side"><button class="complete-button" data-complete-plan="${p.id}"><i data-lucide="check"></i> Mark completed</button><button class="delete-button" data-delete-plan="${p.id}" aria-label="Delete plan"><i data-lucide="trash-2"></i></button></div></article>`).join("");
 $("#bucketList").innerHTML=data.bucket.map(b=>`<article class="bucket-card"><span class="status">${b.status}</span><span class="eyebrow">${esc(b.location)}</span><h3>${esc(b.name)}</h3><p>${esc(b.notes)}</p><div class="plan-details">${tagsHtml([b.season,b.priority,b.cost].filter(Boolean))}</div><button class="bucket-delete" data-delete-bucket="${b.id}" aria-label="Delete dream"><i data-lucide="trash-2"></i></button></article>`).join("");
 $("#planCountBadge").textContent=data.plans.length;$("#plannedTabCount").textContent=data.plans.length;$("#bucketTabCount").textContent=data.bucket.length
}
function renderStats(){
 const s=getStats(),g=data.goals,pct=Math.min(100,Math.round(s.distance/g.distance*100));
 $("#distanceStat").innerHTML=`${s.distance.toFixed(1)} <small>mi</small>`;$("#elevationStat").innerHTML=`${Math.round(s.elevation).toLocaleString()} <small>ft</small>`;$("#hikesStat").innerHTML=`${s.hikes} <small>hikes</small>`;$("#timeStat").innerHTML=`${s.duration.toFixed(1)} <small>hrs</small>`;
 $("#rainierComparison").textContent=`${(s.elevation/14411).toFixed(1)} Mount Rainiers`;$("#heroPercent").textContent=`${pct}%`;$("#heroGoalLabel").textContent=`${s.distance.toFixed(1)} of ${g.distance} miles`;$(".sidebar-card strong").innerHTML=`<span id="sideGoalMiles">${s.distance.toFixed(1)}</span> / ${g.distance} mi`;$("#sideGoalBar").style.width=`${pct}%`;$("#sideGoalText").textContent=`${Math.max(0,g.distance-s.distance).toFixed(1)} miles to go`;
 const goalRow=(value,target,label,unit,color)=>{const p=Math.min(100,Math.round(value/target*100));return`<div class="goal-ring" style="--value:${p};--ring:${color}"><span>${p}%</span></div><div><strong>${label}</strong><span>${Math.round(value).toLocaleString()} of ${target.toLocaleString()} ${unit}</span><div class="progress-track"><span style="width:${p}%"></span></div></div>`};$("#distanceGoalRow").innerHTML=goalRow(s.distance,g.distance,"Distance explorer","miles","#e89545");$("#elevationGoalRow").innerHTML=goalRow(s.elevation,g.elevation,"Reach new heights","feet","#5e8e78");$("#hikesGoalRow").innerHTML=goalRow(s.hikes,g.hikes,"Hike more often","hikes","#5f7f9e")
}
function renderInsights(){
 const s=getStats(),long=[...data.hikes].sort((a,b)=>b.distance-a.distance)[0],climb=[...data.hikes].sort((a,b)=>b.elevation-a.elevation)[0],high=[...data.hikes].sort((a,b)=>b.highest-a.highest)[0],avg=s.hikes?s.distance/s.hikes:0,regions={};data.hikes.forEach(h=>regions[h.location]=(regions[h.location]||0)+1);const favorite=Object.entries(regions).sort((a,b)=>b[1]-a[1])[0]?.[0]||"None yet";
 $("#comparisonGrid").innerHTML=[["mountain-snow",`${(s.elevation/29032).toFixed(2)}× Everest`,"Lifetime elevation"],["building-2",`${(s.elevation/1454).toFixed(1)} Empire State Buildings`,"One step at a time"],["medal",`${(s.distance/26.2).toFixed(1)} marathons`,"Lifetime distance"],["route",`${avg.toFixed(1)} miles`,"Average hike"]].map(x=>`<article class="comparison-card"><i data-lucide="${x[0]}"></i><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join("");
 $("#recordList").innerHTML=[["Longest hike",long?`${long.name} · ${long.distance} mi`:"None"],["Most climbing",climb?`${climb.name} · ${climb.elevation.toLocaleString()} ft`:"None"],["Highest point",high?`${high.name} · ${(+high.highest).toLocaleString()} ft`:"None"],["Favorite region",favorite]].map(x=>`<div><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join("");
 $("#hideLocations").checked=data.settings.hideLocations;$("#lntSetting").checked=data.settings.lnt
}
function renderAll(){renderRecent();renderHikes();renderPlans();renderStats();renderInsights();icons()}

function showView(name){$$(".view").forEach(v=>v.classList.remove("active"));$(`#${name}View`).classList.add("active");$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$("#pageTitle").textContent={dashboard:"Good morning, Nicky",hikes:"Your hiking journal",plans:"Plan the next adventure",map:"Explore your trails",insights:"Celebrate your progress"}[name];window.scrollTo({top:0,behavior:"smooth"});if(name==="map")setTimeout(initMap,50)}
function openModal(type,item=null){$("#entryForm").reset();$("#entryType").value=type;$("#editId").value=item?.id||"";$("#entryDate").value=item?.date||new Date().toISOString().slice(0,10);const cfg={completed:["Save a memory",item?"Edit completed hike":"Log a completed hike",item?"Update hike":"Save hike"],planned:["Make a plan","Add a future hike","Save plan"],bucket:["Dream a little bigger","Add to bucket list","Save dream"]}[type];$("#dialogEyebrow").textContent=cfg[0];$("#dialogTitle").textContent=cfg[1];$("#saveEntryBtn").lastChild.textContent=` ${cfg[2]}`;$("#dateField").style.display=type==="bucket"?"none":"grid";$("#ratingField").style.display=type==="completed"?"grid":"none";if(item)fillForm(item);$("#entryDialog").showModal()}
function fillForm(x){const m={Name:"name",Location:"location",Date:"date",Distance:"distance",Elevation:"elevation",Difficulty:"difficulty",Rating:"rating",Duration:"duration",Highest:"highest",Tags:"tags",Notes:"notes",Trailhead:"trailhead",Weather:"weather",Conditions:"conditions",Crowds:"crowds",Parking:"parking",Permit:"permit",Cell:"cell",Dog:"dog",Water:"water",Wildlife:"wildlife",Gear:"gear",Safety:"safety",Link:"link"};Object.entries(m).forEach(([id,key])=>{const el=$(`#entry${id}`);if(el)el.value=key==="tags"?(x.tags||[]).join(", "):(x[key]??"")})}
async function readPhotos(files){return Promise.all([...files].slice(0,4).map(file=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,src:r.result,caption:file.name});r.readAsDataURL(file)})))}
async function readRoute(file){if(!file)return[];const xml=new DOMParser().parseFromString(await file.text(),"text/xml"),pts=[...xml.querySelectorAll("trkpt, rtept, Point coordinates")];return pts.map(p=>{if(p.matches("Point coordinates")){const [lng,lat,ele]=p.textContent.trim().split(",").map(Number);return{lat,lng,ele}}return{lat:+p.getAttribute("lat"),lng:+p.getAttribute("lon"),ele:+p.querySelector("ele")?.textContent||0}}).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng))}
function formItem(){return{name:$("#entryName").value,location:$("#entryLocation").value,date:$("#entryDate").value||new Date().toISOString().slice(0,10),distance:+$("#entryDistance").value,elevation:+$("#entryElevation").value,difficulty:$("#entryDifficulty").value,rating:+$("#entryRating").value,duration:+$("#entryDuration").value,highest:+$("#entryHighest").value,tags:$("#entryTags").value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean),notes:$("#entryNotes").value,trailhead:$("#entryTrailhead").value,weather:$("#entryWeather").value,conditions:$("#entryConditions").value,crowds:$("#entryCrowds").value,parking:$("#entryParking").value,permit:$("#entryPermit").value,cell:$("#entryCell").value,dog:$("#entryDog").value,water:$("#entryWater").value,wildlife:$("#entryWildlife").value,gear:$("#entryGear").value,safety:$("#entrySafety").value,link:$("#entryLink").value}}
function showDetail(id){const h=data.hikes.find(x=>x.id==id);if(!h)return;detailId=h.id;$("#detailTitle").textContent=h.name;$("#detailLocation").textContent=`${h.location} · ${fmtDate(h.date)}`;$("#detailPhotos").innerHTML=h.photos.length?h.photos.map(p=>`<img src="${p.src}" alt="${esc(p.caption||`${h.name} hiking photo`)}">`).join(""):`<div class="empty-photo"><i data-lucide="image"></i><span>No photos yet</span></div>`;$("#detailStats").innerHTML=[["route",`${h.distance} mi`],["mountain",`${(+h.elevation).toLocaleString()} ft gain`],["clock",`${h.duration||0} hrs`],["move-up",`${(+h.highest||0).toLocaleString()} ft high`]].map(x=>`<span><i data-lucide="${x[0]}"></i><strong>${x[1]}</strong></span>`).join("");$("#detailBody").innerHTML=`<section><h3>Reflection</h3><p>${esc(h.notes||"No reflection yet.")}</p><div class="plan-details">${tagsHtml(h.tags)}</div></section><section><h3>Conditions & weather</h3><p>${esc(h.conditions||"No condition notes")} · ${esc(h.weather||"No weather notes")} · ${esc(h.crowds||"Unknown")} crowds</p></section><section><h3>Practical notes</h3><dl><dt>Parking / pass</dt><dd>${esc(h.parking||"Unknown")}</dd><dt>Permit</dt><dd>${esc(h.permit||"Unknown")}</dd><dt>Cell service</dt><dd>${esc(h.cell||"Unknown")}</dd><dt>Water / bathrooms</dt><dd>${esc(h.water||"Unknown")}</dd><dt>Safety / wildlife</dt><dd>${esc([h.safety,h.wildlife].filter(Boolean).join(" · ")||"No notes")}</dd><dt>Gear</dt><dd>${esc(h.gear||"No notes")}</dd></dl></section>`;$("#gpxExportBtn").disabled=!h.route.length;$("#detailDialog").showModal();icons()}
function initMap(){if(!window.L)return;if(map){map.remove();map=null}map=L.map("map",{zoomControl:false}).setView([47.3,-121.7],7);L.control.zoom({position:"bottomright"}).addTo(map);const standard=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors"}).addTo(map),topo=L.tileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenTopoMap"});L.control.layers({"Standard":standard,"Topographic":topo}).addTo(map);[["hikes","#277a59","Completed"],["plans","#e89545","Planned"],["bucket","#7189ad","Bucket list"]].forEach(([key,color,label])=>data[key].forEach(item=>{const offset=data.settings.hideLocations ? .025 : 0,first=item.route[0],lat=(first?.lat||item.lat),lng=(first?.lng||item.lng);if(!lat)return;const icon=L.divIcon({className:"",html:`<div class="map-pin" style="background:${color}"></div>`,iconSize:[20,20],iconAnchor:[10,18]});L.marker([lat+offset,lng+offset],{icon}).addTo(map).bindPopup(`<strong>${esc(item.name)}</strong><br><small>${label} · ${esc(item.location)}</small>`);if(item.route.length)L.polyline(item.route.map(p=>[p.lat+offset,p.lng+offset]),{color,weight:4}).addTo(map)}))}
function gpxFor(h){const pts=h.route.map(p=>`<trkpt lat="${p.lat}" lon="${p.lng}"><ele>${p.ele||0}</ele></trkpt>`).join("");return`<?xml version="1.0"?><gpx version="1.1" creator="Nickys Hiking Pal"><trk><name>${esc(h.name)}</name><trkseg>${pts}</trkseg></trk></gpx>`}

document.addEventListener("click",e=>{const view=e.target.closest("[data-view]")?.dataset.view||e.target.closest("[data-view-jump]")?.dataset.viewJump||e.target.closest("[data-view-link]")?.dataset.viewLink;if(view){e.preventDefault();showView(view)}const modal=e.target.closest("[data-open-modal]")?.dataset.openModal;if(modal)openModal(modal);const detail=e.target.closest("[data-detail]")?.dataset.detail;if(detail&&!e.target.closest("[data-delete-hike]"))showDetail(detail);const del=e.target.closest("[data-delete-hike]")?.dataset.deleteHike;if(del&&confirm("Delete this hike from your journal?")){data.hikes=data.hikes.filter(h=>h.id!=del);save();renderAll();toast("Hike removed")}const dp=e.target.closest("[data-delete-plan]")?.dataset.deletePlan;if(dp){data.plans=data.plans.filter(x=>x.id!=dp);save();renderAll();toast("Plan removed")}const db=e.target.closest("[data-delete-bucket]")?.dataset.deleteBucket;if(db){data.bucket=data.bucket.filter(x=>x.id!=db);save();renderAll();toast("Dream removed")}const complete=e.target.closest("[data-complete-plan]")?.dataset.completePlan;if(complete){const p=data.plans.find(x=>x.id==complete);data.plans=data.plans.filter(x=>x.id!=complete);data.hikes.unshift({...p,id:Date.now(),date:new Date().toISOString().slice(0,10),rating:5,notes:`Completed from plan. ${p.notes}`});save();renderAll();toast(`${p.name} moved to completed hikes`)}if(e.target.closest("[data-close-detail]"))$("#detailDialog").close()});
$("#entryForm").addEventListener("submit",async e=>{e.preventDefault();const type=$("#entryType").value,id=+$("#editId").value,item={id:id||Date.now(),...formItem()},old=id?data.hikes.find(x=>x.id===id):null;item.photos=(await readPhotos($("#entryPhotos").files)).concat(old?.photos||[]);item.route=(await readRoute($("#entryRoute").files[0]));if(!item.route.length)item.route=old?.route||[];if(item.route[0]){item.lat=item.route[0].lat;item.lng=item.route[0].lng}if(type==="completed"){data.hikes=id?data.hikes.map(x=>x.id===id?item:x):[item,...data.hikes]}else if(type==="planned"){item.checklist=(item.gear||"Ten essentials, water, offline map").split(",").map(x=>({text:x.trim(),done:false}));data.plans.unshift(item)}else data.bucket.unshift({...item,status:"Dreaming",season:item.weather||"Any season",priority:"Medium"});try{save()}catch{item.photos=[];save();toast("Saved without photos because browser storage is full")}renderAll();$("#entryDialog").close();toast(id?"Hike updated":type==="completed"?"Hike saved to your journal":type==="planned"?"Plan added to your calendar":"Dream added to your bucket list")});
["hikeSearch","difficultyFilter","tagFilter","sortHikes"].forEach(id=>$(`#${id}`).addEventListener(id==="hikeSearch"?"input":"change",()=>{renderHikes();icons()}));
$$("[data-plan-tab]").forEach(b=>b.addEventListener("click",()=>{$$("[data-plan-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#plannedList").classList.toggle("hidden",b.dataset.planTab!=="planned");$("#bucketList").classList.toggle("hidden",b.dataset.planTab!=="bucket")}));
document.addEventListener("change",e=>{if(e.target.dataset.check){const [id,i]=e.target.dataset.check.split(":");const p=data.plans.find(x=>x.id==id);p.checklist[i]=typeof p.checklist[i]==="string"?{text:p.checklist[i],done:e.target.checked}:{...p.checklist[i],done:e.target.checked};save()}});
$("#exportBtn").addEventListener("click",()=>download("nickys-hiking-pal-backup.json",JSON.stringify(data,null,2),"application/json"));$("#importBtn").addEventListener("click",()=>$("#backupInput").click());$("#backupInput").addEventListener("change",async e=>{try{data=JSON.parse(await e.target.files[0].text());data.hikes.forEach(normalize);data.plans.forEach(normalize);data.bucket.forEach(normalize);save();renderAll();toast("Backup restored")}catch{toast("That backup could not be read")}});
$("#csvExportBtn").addEventListener("click",()=>download("hike-history.csv",["Name,Date,Location,Distance,Elevation,Duration,Difficulty,Rating,Tags",...data.hikes.map(h=>[h.name,h.date,h.location,h.distance,h.elevation,h.duration,h.difficulty,h.rating,h.tags.join("|")].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n"),"text/csv"));
$("#searchToggle").addEventListener("click",()=>{showView("hikes");setTimeout(()=>$("#hikeSearch").focus(),100)});$("#editGoalsBtn").addEventListener("click",()=>{for(const [key,label] of [["distance","Annual miles"],["elevation","Annual elevation feet"],["hikes","Annual hike count"],["bucket","Annual bucket-list completions"],["monthly","Monthly miles"]]){const next=prompt(`${label}:`,data.goals[key]);if(next&&+next>0)data.goals[key]=+next}save();renderStats();toast("Goals updated")});
$("#privacyBtn").addEventListener("click",()=>{showView("insights");toast("Your data stays in this browser until you export it")});$("#hideLocations").addEventListener("change",e=>{data.settings.hideLocations=e.target.checked;save();toast(e.target.checked?"Exact trailheads hidden":"Exact trailheads visible")});$("#lntSetting").addEventListener("change",e=>{data.settings.lnt=e.target.checked;save();renderPlans();icons()});$("#printPlanBtn").addEventListener("click",()=>window.print());
$("#favoriteBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);h.favorite=!h.favorite;save();renderAll();showDetail(detailId);toast(h.favorite?"Added to favorites":"Removed from favorites")});$("#duplicateBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);data.plans.unshift({...structuredClone(h),id:Date.now(),date:new Date().toISOString().slice(0,10),checklist:[{text:"Check current conditions",done:false},{text:"Pack ten essentials",done:false}]});save();renderAll();$("#detailDialog").close();toast("Hike duplicated as a plan")});$("#gpxExportBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);if(h.route.length)download(`${h.name.replace(/\W+/g,"-").toLowerCase()}.gpx`,gpxFor(h),"application/gpx+xml")});$("#editHikeBtn").addEventListener("click",()=>{const h=data.hikes.find(x=>x.id===detailId);$("#detailDialog").close();openModal("completed",h)});
const periodStats={week:["5.7","1,768","1","3.5"],month:["15.3","4,890","3","9.2"],year:["84.2","22,980","14","41.5"],lifetime:["486.7","121,440","78","248"]};$$("[data-period]").forEach(b=>b.addEventListener("click",()=>{const s=periodStats[b.dataset.period];$$("[data-period]").forEach(x=>x.classList.toggle("active",x===b));$("#distanceStat").innerHTML=`${s[0]} <small>mi</small>`;$("#elevationStat").innerHTML=`${s[1]} <small>ft</small>`;$("#hikesStat").innerHTML=`${s[2]} <small>hikes</small>`;$("#timeStat").innerHTML=`${s[3]} <small>hrs</small>`}));
$("#todayLabel").textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"});if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});renderAll();
